apiVersion: apps/v1
kind: Deployment
metadata:
  name: actors-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actors
  template:
    metadata:
      labels:
        app: actors
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "actors"
        dapr.io/app-port: "5050"
    spec:
      containers:
        - name: actors-host
          image: {{ .Values.PrivateContainerRegistry }}dnw-dapr-pubsub-actors:latest
          ports:
            - containerPort: 5050