apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "checkout"
        dapr.io/app-port: "5050"
    spec:
      containers:
        - name: checkout
          image: "{{ .Values.PrivateContainerRegistry }}dnw-dapr-pubsub-checkout:latest"
          ports:
            - containerPort: 5050