{{- if eq .Values.PubSubType "Kafka" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.3.0
          ports:
            - containerPort: {{ .Values.KafkaPort }}
            - containerPort: {{ .Values.KafkaBrokerPort }}
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:{{ .Values.ZookeeperPort }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:{{ .Values.KafkaPort }},PLAINTEXT_INTERNAL://kafka-service:{{ .Values.KafkaBrokerPort }}"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: default  
      port: {{ .Values.KafkaPort }}
      targetPort: {{ .Values.KafkaPort }}
    - name: broker  
      port: {{ .Values.KafkaBrokerPort }}
      targetPort: {{ .Values.KafkaBrokerPort }}
{{- end }}
  